/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package computability;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void testMain() {
        App app = new App();
        assertNotNull(app);
    }
}
