/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package computability;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.run();
    }
}
