import type { Language } from "./i18n";

export type AlgorithmTheoryId =
  | "thompson"
  | "subset_construction"
  | "dfa_minimization"
  | "state_elimination"
  | "epsilon_elimination"
  | "remove_unreachable"
  | "dfa_equivalence"
  | "regular_grammar_to_nfa"
  | "cfg_to_pda"
  | "chomsky_normal_form"
  | "cyk"
  | "ll1_analysis"
  | "regular_pumping"
  | "context_free_pumping";

type Localized = Record<Language, string>;

export type AlgorithmTheory = {
  definition: Localized;
  notation: Localized;
  prerequisites: Localized;
  procedure: Localized[];
  interpretation: Localized;
  limits: Localized;
  example: Localized;
};

const l = (it: string, en: string, fr: string, de: string, es: string, pt: string): Localized => ({
  it,
  en,
  fr,
  de,
  es,
  pt,
});

const procedure = (first: Localized, second: Localized, third: Localized): Localized[] => [
  first,
  second,
  third,
];

export const algorithmTheory: Record<AlgorithmTheoryId, AlgorithmTheory> = {
  thompson: {
    definition: l(
      "Costruisce un epsilon-NFA equivalente a un'espressione regolare, per induzione sulla sua sintassi.",
      "Builds an epsilon-NFA equivalent to a regular expression by induction on its syntax.",
      "Construit un epsilon-AFN equivalent a une expression reguliere par induction sur sa syntaxe.",
      "Konstruiert durch Induktion einen zu einem regulaeren Ausdruck aequivalenten Epsilon-NEA.",
      "Construye un epsilon-AFN equivalente a una expresion regular por induccion sobre su sintaxis.",
      "Constroi um epsilon-AFN equivalente a uma expressao regular por inducao sobre a sua sintaxe.",
    ),
    notation: l(
      "Per ogni sottoespressione r si crea un frammento N(r) con ingresso i(r) e uscita f(r). epsilon non consuma simboli.",
      "For every subexpression r, create a fragment N(r) with entry i(r) and exit f(r). epsilon consumes no symbol.",
      "Pour chaque sous-expression r, on cree N(r) avec entree i(r) et sortie f(r). epsilon ne consomme aucun symbole.",
      "Fuer jeden Teilausdruck r entsteht N(r) mit Eingang i(r) und Ausgang f(r). Epsilon verbraucht kein Zeichen.",
      "Para cada subexpresion r se crea N(r) con entrada i(r) y salida f(r). epsilon no consume simbolos.",
      "Para cada subexpressao r cria-se N(r) com entrada i(r) e saida f(r). epsilon nao consome simbolos.",
    ),
    prerequisites: l(
      "L'espressione deve usare la sintassi supportata dall'editor: simboli, unione, concatenazione, stella e parentesi.",
      "The expression must use the editor's supported syntax: symbols, union, concatenation, star, and parentheses.",
      "L'expression doit utiliser la syntaxe prise en charge: symboles, union, concatenation, etoile et parentheses.",
      "Der Ausdruck muss die unterstuetzte Syntax verwenden: Zeichen, Vereinigung, Verkettung, Stern und Klammern.",
      "La expresion debe usar la sintaxis admitida: simbolos, union, concatenacion, estrella y parentesis.",
      "A expressao deve usar a sintaxe suportada: simbolos, uniao, concatenacao, estrela e parenteses.",
    ),
    procedure: procedure(
      l(
        "Crea un arco etichettato per ogni simbolo e frammenti epsilon per insieme vuoto ed epsilon.",
        "Create a labeled arc for every symbol and epsilon fragments for empty set and epsilon.",
        "Cree un arc etiquete pour chaque symbole et des fragments epsilon pour vide et epsilon.",
        "Erzeuge eine beschriftete Kante fuer jedes Zeichen und Epsilon-Fragmente fuer leer und Epsilon.",
        "Crea un arco etiquetado por simbolo y fragmentos epsilon para vacio y epsilon.",
        "Crie um arco rotulado por simbolo e fragmentos epsilon para vazio e epsilon.",
      ),
      l(
        "Combina i frammenti: unione biforca, concatenazione collega, stella aggiunge ingresso e uscita nuovi.",
        "Combine fragments: union branches, concatenation joins, star adds a fresh entry and exit.",
        "Combinez les fragments: union bifurque, concatenation relie, etoile ajoute entree et sortie.",
        "Kombiniere Fragmente: Vereinigung verzweigt, Verkettung verbindet, Stern fuegt Ein- und Ausgang hinzu.",
        "Combina fragmentos: union bifurca, concatenacion une, estrella anade entrada y salida nuevas.",
        "Combine fragmentos: uniao bifurca, concatenacao liga, estrela adiciona entrada e saida novas.",
      ),
      l(
        "Marca l'ingresso del frammento finale iniziale e la sua uscita finale.",
        "Mark the final fragment's entry as initial and its exit as accepting.",
        "Marquez l'entree du fragment final initiale et sa sortie finale.",
        "Markiere den Eingang des Endfragments als Start und den Ausgang als akzeptierend.",
        "Marca la entrada del fragmento final como inicial y su salida como final.",
        "Marque a entrada do fragmento final como inicial e a saida como final.",
      ),
    ),
    interpretation: l(
      "Il risultato accetta esattamente L(r); gli stati intermedi descrivono la struttura dell'espressione.",
      "The result accepts exactly L(r); intermediate states describe the expression structure.",
      "Le resultat accepte exactement L(r); les etats intermediaires decrivent la structure de l'expression.",
      "Das Ergebnis akzeptiert genau L(r); Zwischenzustaende beschreiben die Ausdrucksstruktur.",
      "El resultado acepta exactamente L(r); los estados intermedios describen la estructura de la expresion.",
      "O resultado aceita exatamente L(r); os estados intermediarios descrevem a estrutura da expressao.",
    ),
    limits: l(
      "Il numero di stati e lineare nella dimensione dell'espressione. L'automa non e in generale deterministico.",
      "The number of states is linear in expression size. The automaton is not generally deterministic.",
      "Le nombre d'etats est lineaire dans la taille de l'expression. L'automate n'est pas en general deterministe.",
      "Die Zahl der Zustaende ist linear zur Ausdrucksgroesse. Der Automat ist im Allgemeinen nicht deterministisch.",
      "El numero de estados es lineal en el tamano de la expresion. El automata no suele ser determinista.",
      "O numero de estados e linear no tamanho da expressao. O automato em geral nao e deterministico.",
    ),
    example: l(
      "Per a|b, un nuovo ingresso epsilon raggiunge i(a) e i(b), mentre f(a) e f(b) raggiungono una sola uscita.",
      "For a|b, a fresh epsilon entry reaches i(a) and i(b), while f(a) and f(b) reach one exit.",
      "Pour a|b, une nouvelle entree epsilon atteint i(a) et i(b), puis f(a) et f(b) une sortie.",
      "Bei a|b erreicht ein neuer Epsilon-Eingang i(a) und i(b); f(a) und f(b) fuehren zu einem Ausgang.",
      "Para a|b, una nueva entrada epsilon alcanza i(a) e i(b), y f(a), f(b) alcanzan una salida.",
      "Para a|b, uma nova entrada epsilon alcanca i(a) e i(b), e f(a), f(b) alcancam uma saida.",
    ),
  },
  subset_construction: {
    definition: l(
      "Trasforma un epsilon-NFA in un DFA equivalente rappresentando ogni stato DFA come insieme di stati NFA.",
      "Transforms an epsilon-NFA into an equivalent DFA by representing every DFA state as a set of NFA states.",
      "Transforme un epsilon-AFN en AFD equivalent en representant chaque etat AFD par un ensemble d'etats AFN.",
      "Wandelt einen Epsilon-NEA in einen aequivalenten DEA um; jeder DEA-Zustand ist eine NEA-Zustandsmenge.",
      "Transforma un epsilon-AFN en AFD equivalente: cada estado AFD es un conjunto de estados AFN.",
      "Transforma um epsilon-AFN em AFD equivalente: cada estado AFD e um conjunto de estados AFN.",
    ),
    notation: l(
      "E(S) e la chiusura epsilon di S; move(S,a) raccoglie le destinazioni con etichetta a.",
      "E(S) is epsilon closure of S; move(S,a) collects destinations labeled a.",
      "E(S) est la fermeture epsilon de S; move(S,a) collecte les destinations etiquetees a.",
      "E(S) ist der Epsilon-Abschluss von S; move(S,a) sammelt a-Nachfolger.",
      "E(S) es el cierre epsilon de S; move(S,a) reune destinos etiquetados a.",
      "E(S) e o fecho epsilon de S; move(S,a) reune destinos rotulados a.",
    ),
    prerequisites: l(
      "Il modello sorgente deve essere un NFA con stato iniziale e alfabeto definiti.",
      "The source model must be an NFA with an initial state and alphabet.",
      "Le modele source doit etre un AFN avec etat initial et alphabet definis.",
      "Das Quellmodell muss ein NEA mit Startzustand und Alphabet sein.",
      "El modelo fuente debe ser un AFN con estado inicial y alfabeto definidos.",
      "O modelo fonte deve ser um AFN com estado inicial e alfabeto definidos.",
    ),
    procedure: procedure(
      l(
        "Inizia da E({q0}) e usalo come primo stato del DFA.",
        "Start from E({q0}) and use it as the DFA's first state.",
        "Commencez avec E({q0}) comme premier etat de l'AFD.",
        "Beginne mit E({q0}) als erstem DEA-Zustand.",
        "Empieza por E({q0}) como primer estado del AFD.",
        "Comece por E({q0}) como primeiro estado do AFD.",
      ),
      l(
        "Per ogni insieme S e simbolo a, crea la transizione verso E(move(S,a)).",
        "For every set S and symbol a, create the transition to E(move(S,a)).",
        "Pour chaque ensemble S et symbole a, creez la transition vers E(move(S,a)).",
        "Erzeuge fuer jede Menge S und jedes Zeichen a den Uebergang zu E(move(S,a)).",
        "Para cada conjunto S y simbolo a, crea la transicion a E(move(S,a)).",
        "Para cada conjunto S e simbolo a, crie a transicao para E(move(S,a)).",
      ),
      l(
        "Ripeti finche non compaiono nuovi insiemi; accetta gli insiemi che contengono un finale NFA.",
        "Repeat until no new sets appear; accept sets containing an NFA final state.",
        "Repetez jusqu'a absence de nouvel ensemble; acceptez ceux contenant un final AFN.",
        "Wiederhole bis keine neuen Mengen erscheinen; akzeptiere Mengen mit einem NEA-Endzustand.",
        "Repite hasta que no haya conjuntos nuevos; acepta los que contienen un final AFN.",
        "Repita ate nao surgirem conjuntos novos; aceite os que contiverem um final AFN.",
      ),
    ),
    interpretation: l(
      "Ogni cammino nel DFA riassume tutti i cammini possibili dell'NFA dopo la stessa parola.",
      "Each DFA path summarizes all possible NFA paths after the same word.",
      "Chaque chemin AFD resume tous les chemins AFN possibles apres le meme mot.",
      "Jeder DEA-Pfad fasst alle moeglichen NEA-Pfade nach demselben Wort zusammen.",
      "Cada camino AFD resume todos los caminos posibles del AFN tras la misma palabra.",
      "Cada caminho AFD resume todos os caminhos possiveis do AFN apos a mesma palavra.",
    ),
    limits: l(
      "Nel caso peggiore produce fino a 2^|Q| stati; gli insiemi irraggiungibili non vengono creati.",
      "In the worst case it produces up to 2^|Q| states; unreachable sets are not created.",
      "Au pire, jusqu'a 2^|Q| etats; les ensembles inaccessibles ne sont pas crees.",
      "Im schlimmsten Fall entstehen bis zu 2^|Q| Zustaende; unerreichbare Mengen werden nicht erzeugt.",
      "En el peor caso produce hasta 2^|Q| estados; no crea conjuntos inalcanzables.",
      "No pior caso produz ate 2^|Q| estados; conjuntos inacessiveis nao sao criados.",
    ),
    example: l(
      "Se E({q0})={q0,q1} e con a si raggiunge q2, la transizione porta a E({q2}).",
      "If E({q0})={q0,q1} and a reaches q2, the transition goes to E({q2}).",
      "Si E({q0})={q0,q1} et a atteint q2, la transition va vers E({q2}).",
      "Wenn E({q0})={q0,q1} und a q2 erreicht, fuehrt der Uebergang zu E({q2}).",
      "Si E({q0})={q0,q1} y a alcanza q2, la transicion va a E({q2}).",
      "Se E({q0})={q0,q1} e a alcanca q2, a transicao vai para E({q2}).",
    ),
  },
  dfa_minimization: {
    definition: l(
      "Costruisce il DFA minimo fondendo gli stati che riconoscono lo stesso linguaggio residuo.",
      "Builds the minimum DFA by merging states that recognize the same residual language.",
      "Construit l'AFD minimal en fusionnant les etats reconnaissant le meme langage residuel.",
      "Konstruiert den minimalen DEA durch Verschmelzen von Zustaenden mit gleicher Restsprache.",
      "Construye el AFD minimo fusionando estados que reconocen el mismo lenguaje residual.",
      "Constroi o AFD minimo fundindo estados que reconhecem a mesma linguagem residual.",
    ),
    notation: l(
      "p e q sono equivalenti se per ogni parola w, delta*(p,w) e delta*(q,w) hanno la stessa accettazione.",
      "p and q are equivalent when for every word w, delta*(p,w) and delta*(q,w) have the same acceptance.",
      "p et q sont equivalents si, pour tout mot w, delta*(p,w) et delta*(q,w) ont la meme acceptation.",
      "p und q sind aequivalent, wenn delta*(p,w) und delta*(q,w) fuer jedes w gleich akzeptieren.",
      "p y q son equivalentes si para toda palabra w, delta*(p,w) y delta*(q,w) aceptan igual.",
      "p e q sao equivalentes se, para toda palavra w, delta*(p,w) e delta*(q,w) aceitam de modo igual.",
    ),
    prerequisites: l(
      "Occorre un DFA deterministico; completare le transizioni mancanti con uno stato pozzo se necessario.",
      "A deterministic DFA is required; complete missing transitions with a sink state if necessary.",
      "Un AFD deterministe est requis; completez les transitions manquantes par un puits si besoin.",
      "Ein deterministischer DEA ist erforderlich; ergaenze fehlende Uebergaenge bei Bedarf mit einem Sinkzustand.",
      "Se requiere un AFD determinista; completa transiciones ausentes con un estado pozo si hace falta.",
      "E necessario um AFD deterministico; complete transicoes ausentes com um estado sumidouro se preciso.",
    ),
    procedure: procedure(
      l(
        "Separa inizialmente stati finali e non finali.",
        "Initially separate accepting and non-accepting states.",
        "Separez d'abord les etats finaux et non finaux.",
        "Trenne zuerst akzeptierende und nicht akzeptierende Zustaende.",
        "Separa inicialmente estados finales y no finales.",
        "Separe inicialmente estados finais e nao finais.",
      ),
      l(
        "Raffina ogni blocco quando due stati puntano, per un simbolo, a blocchi diversi.",
        "Refine a block whenever two states point, on a symbol, to different blocks.",
        "Raffinez un bloc quand deux etats pointent, sur un symbole, vers des blocs differents.",
        "Verfeinere einen Block, wenn zwei Zustaende mit einem Zeichen in verschiedene Bloecke fuehren.",
        "Refina un bloque si dos estados apuntan, con un simbolo, a bloques distintos.",
        "Refine um bloco quando dois estados apontam, por um simbolo, para blocos diferentes.",
      ),
      l(
        "Quando la partizione e stabile, ogni blocco diventa uno stato del quoziente.",
        "When the partition is stable, every block becomes one quotient state.",
        "Quand la partition est stable, chaque bloc devient un etat du quotient.",
        "Ist die Partition stabil, wird jeder Block ein Quotientenzustand.",
        "Cuando la particion es estable, cada bloque se vuelve un estado del cociente.",
        "Quando a particao e estavel, cada bloco torna-se um estado do quociente.",
      ),
    ),
    interpretation: l(
      "Il risultato e unico a isomorfismo e conserva il linguaggio del DFA sorgente.",
      "The result is unique up to isomorphism and preserves the source DFA language.",
      "Le resultat est unique a isomorphisme pres et conserve le langage source.",
      "Das Ergebnis ist bis auf Isomorphie eindeutig und erhaelt die Quellsprache.",
      "El resultado es unico salvo isomorfismo y conserva el lenguaje fuente.",
      "O resultado e unico a isomorfismo e preserva a linguagem fonte.",
    ),
    limits: l(
      "Il raffinamento e polinomiale; rimuovere prima gli irraggiungibili semplifica il modello ma non e necessario per la correttezza.",
      "Refinement is polynomial; removing unreachable states first simplifies the model but is not required for correctness.",
      "Le raffinement est polynomial; retirer les inaccessibles simplifie sans etre requis pour la correction.",
      "Die Verfeinerung ist polynomiell; unerreichbare Zustaende vorher zu entfernen vereinfacht, ist aber nicht noetig.",
      "El refinamiento es polinomial; quitar inalcanzables simplifica pero no es necesario para la correccion.",
      "O refinamento e polinomial; remover inacessiveis simplifica, mas nao e necessario para a correcao.",
    ),
    example: l(
      "Due stati non finali con le stesse transizioni verso gli stessi blocchi restano nello stesso blocco.",
      "Two non-final states with transitions into the same blocks remain in one block.",
      "Deux etats non finaux dont les transitions vont vers les memes blocs restent ensemble.",
      "Zwei nicht finale Zustaende mit Uebergaengen in dieselben Bloecke bleiben zusammen.",
      "Dos estados no finales con transiciones a los mismos bloques permanecen juntos.",
      "Dois estados nao finais com transicoes para os mesmos blocos permanecem juntos.",
    ),
  },
  state_elimination: {
    definition: l(
      "Converte un automa finito in un'espressione regolare eliminando stati da un GNFA.",
      "Converts a finite automaton into a regular expression by eliminating states from a GNFA.",
      "Convertit un automate fini en expression reguliere en eliminant les etats d'un GNFA.",
      "Wandelt einen endlichen Automaten durch Zustandsextraktion aus einem GNFA in einen regulaeren Ausdruck um.",
      "Convierte un automata finito en expresion regular eliminando estados de un GNFA.",
      "Converte um automato finito em expressao regular eliminando estados de um GNFA.",
    ),
    notation: l(
      "Rij etichetta tutti i cammini diretti da i a j. Eliminando k: Rij := Rij | Rik(Rkk)*Rkj.",
      "Rij labels all direct paths from i to j. Eliminating k: Rij := Rij | Rik(Rkk)*Rkj.",
      "Rij etiquette tous les chemins directs de i a j. Eliminer k: Rij := Rij | Rik(Rkk)*Rkj.",
      "Rij beschriftet direkte Wege von i nach j. Beim Entfernen von k: Rij := Rij | Rik(Rkk)*Rkj.",
      "Rij etiqueta todos los caminos directos de i a j. Al eliminar k: Rij := Rij | Rik(Rkk)*Rkj.",
      "Rij rotula todos os caminhos diretos de i para j. Ao eliminar k: Rij := Rij | Rik(Rkk)*Rkj.",
    ),
    prerequisites: l(
      "Il sorgente puo essere DFA o NFA; l'algoritmo introduce un unico nuovo iniziale e un unico nuovo finale.",
      "The source may be a DFA or NFA; the algorithm introduces one fresh start and one fresh final state.",
      "La source peut etre AFD ou AFN; l'algorithme introduit un nouveau debut et une nouvelle fin uniques.",
      "Die Quelle kann DEA oder NEA sein; der Algorithmus fuegt einen neuen einzigen Start- und Endzustand ein.",
      "La fuente puede ser AFD o AFN; el algoritmo introduce un nuevo inicial y un nuevo final unicos.",
      "A fonte pode ser AFD ou AFN; o algoritmo introduz um novo inicial e um novo final unicos.",
    ),
    procedure: procedure(
      l(
        "Trasforma ogni arco in una etichetta di espressione regolare e unisci gli archi paralleli con |.",
        "Turn every arc into a regular-expression label and join parallel arcs with |.",
        "Transformez chaque arc en etiquette reguliere et unissez les arcs paralleles avec |.",
        "Wandle jede Kante in ein regulaeres Label um und vereinige parallele Kanten mit |.",
        "Convierte cada arco en etiqueta regular y une arcos paralelos con |.",
        "Transforme cada arco em rotulo regular e una arcos paralelos com |.",
      ),
      l(
        "Scegli uno stato interno k e aggiorna tutte le etichette che lo attraversano.",
        "Choose an internal state k and update every label that passes through it.",
        "Choisissez un etat interne k et mettez a jour chaque etiquette qui le traverse.",
        "Waehle einen inneren Zustand k und aktualisiere jedes Label, das ihn durchlaeuft.",
        "Elige un estado interno k y actualiza cada etiqueta que lo atraviesa.",
        "Escolha um estado interno k e atualize cada rotulo que o atravessa.",
      ),
      l(
        "Elimina tutti gli interni: l'etichetta dall'iniziale al finale e l'espressione ottenuta.",
        "Eliminate all internal states: the start-to-final label is the resulting expression.",
        "Eliminez tous les internes: l'etiquette debut-fin est l'expression resultante.",
        "Entferne alle inneren Zustaende: das Label von Start zu Ende ist der Ergebnis-Ausdruck.",
        "Elimina todos los internos: la etiqueta inicial-final es la expresion resultante.",
        "Elimine todos os internos: o rotulo inicial-final e a expressao resultante.",
      ),
    ),
    interpretation: l(
      "L'espressione riconosce esattamente il linguaggio dell'automa; forme diverse possono essere equivalenti.",
      "The expression recognizes exactly the automaton language; different forms can be equivalent.",
      "L'expression reconnait exactement le langage de l'automate; des formes differentes peuvent etre equivalentes.",
      "Der Ausdruck erkennt genau die Automatensprache; verschiedene Formen koennen aequivalent sein.",
      "La expresion reconoce exactamente el lenguaje del automata; formas distintas pueden ser equivalentes.",
      "A expressao reconhece exatamente a linguagem do automato; formas diferentes podem ser equivalentes.",
    ),
    limits: l(
      "L'ordine di eliminazione cambia molto la dimensione dell'espressione, che puo crescere esponenzialmente.",
      "Elimination order greatly changes expression size, which can grow exponentially.",
      "L'ordre d'elimination change fortement la taille, qui peut croitre exponentiellement.",
      "Die Eliminationsreihenfolge beeinflusst die Ausdrucksgroesse stark; sie kann exponentiell wachsen.",
      "El orden de eliminacion cambia mucho el tamano, que puede crecer exponencialmente.",
      "A ordem de eliminacao altera muito o tamanho, que pode crescer exponencialmente.",
    ),
    example: l(
      "Eliminando k tra i e j, un percorso i-k-j diventa la concatenazione Rik Rkj; un ciclo su k diventa (Rkk)*.",
      "Eliminating k between i and j turns i-k-j into Rik Rkj; a loop on k becomes (Rkk)*.",
      "Eliminer k entre i et j transforme i-k-j en Rik Rkj; une boucle sur k devient (Rkk)*.",
      "Das Entfernen von k zwischen i und j macht i-k-j zu Rik Rkj; eine Schleife wird (Rkk)*.",
      "Eliminar k entre i y j convierte i-k-j en Rik Rkj; un ciclo sobre k es (Rkk)*.",
      "Eliminar k entre i e j transforma i-k-j em Rik Rkj; um ciclo em k torna-se (Rkk)*.",
    ),
  },
  epsilon_elimination: {
    definition: l(
      "Rimuove le transizioni epsilon da un NFA senza modificare il linguaggio riconosciuto.",
      "Removes epsilon transitions from an NFA without changing its recognized language.",
      "Supprime les transitions epsilon d'un AFN sans modifier le langage reconnu.",
      "Entfernt Epsilon-Uebergaenge aus einem NEA ohne dessen Sprache zu aendern.",
      "Elimina transiciones epsilon de un AFN sin cambiar su lenguaje reconocido.",
      "Remove transicoes epsilon de um AFN sem alterar a linguagem reconhecida.",
    ),
    notation: l(
      "E(q) e l'insieme degli stati raggiungibili da q con zero o piu epsilon. delta'(q,a)=E(move(E(q),a)).",
      "E(q) is the states reachable from q by zero or more epsilon moves. delta'(q,a)=E(move(E(q),a)).",
      "E(q) est l'ensemble atteignable de q par zero ou plusieurs epsilon. delta'(q,a)=E(move(E(q),a)).",
      "E(q) sind von q mit null oder mehr Epsilon erreichbare Zustaende. delta'(q,a)=E(move(E(q),a)).",
      "E(q) son estados alcanzables desde q por cero o mas epsilon. delta'(q,a)=E(move(E(q),a)).",
      "E(q) sao estados alcancaveis de q por zero ou mais epsilon. delta'(q,a)=E(move(E(q),a)).",
    ),
    prerequisites: l(
      "Serve un NFA; epsilon e una transizione silenziosa, non un simbolo dell'alfabeto.",
      "An NFA is required; epsilon is a silent transition, not an alphabet symbol.",
      "Un AFN est requis; epsilon est une transition silencieuse, pas un symbole de l'alphabet.",
      "Ein NEA ist erforderlich; Epsilon ist ein stiller Uebergang, kein Alphabetzeichen.",
      "Se requiere un AFN; epsilon es una transicion silenciosa, no un simbolo del alfabeto.",
      "E necessario um AFN; epsilon e uma transicao silenciosa, nao um simbolo do alfabeto.",
    ),
    procedure: procedure(
      l(
        "Calcola E(q) per ogni stato q.",
        "Compute E(q) for every state q.",
        "Calculez E(q) pour chaque etat q.",
        "Berechne E(q) fuer jeden Zustand q.",
        "Calcula E(q) para cada estado q.",
        "Calcule E(q) para cada estado q.",
      ),
      l(
        "Per ogni q e a, aggiungi gli archi verso E(move(E(q),a)).",
        "For every q and a, add arcs to E(move(E(q),a)).",
        "Pour chaque q et a, ajoutez les arcs vers E(move(E(q),a)).",
        "Fuege fuer jedes q und a Kanten zu E(move(E(q),a)) hinzu.",
        "Para cada q y a, anade arcos a E(move(E(q),a)).",
        "Para cada q e a, adicione arcos para E(move(E(q),a)).",
      ),
      l(
        "Rendi finale q se E(q) contiene un finale originale, poi rimuovi tutti gli epsilon.",
        "Make q accepting if E(q) contains an original final, then remove all epsilon arcs.",
        "Rendez q final si E(q) contient un final original, puis retirez tous les epsilon.",
        "Mache q akzeptierend, falls E(q) einen alten Endzustand enthaelt, dann entferne alle Epsilon-Kanten.",
        "Haz q final si E(q) contiene un final original y elimina todos los epsilon.",
        "Torne q final se E(q) contem um final original e remova todos os epsilon.",
      ),
    ),
    interpretation: l(
      "Ogni vecchia computazione con epsilon ha una computazione corrispondente che legge gli stessi simboli.",
      "Every former epsilon computation has a corresponding computation reading the same symbols.",
      "Toute ancienne computation epsilon a une computation correspondante lisant les memes symboles.",
      "Jede fruehere Epsilon-Berechnung hat eine entsprechende Berechnung mit denselben gelesenen Zeichen.",
      "Toda computacion epsilon anterior tiene una computacion correspondiente que lee los mismos simbolos.",
      "Toda computacao epsilon anterior tem uma computacao correspondente que le os mesmos simbolos.",
    ),
    limits: l(
      "Le nuove transizioni possono aumentare; il risultato resta un NFA e puo richiedere determinizzazione successiva.",
      "The new transitions can increase; the result remains an NFA and may still require determinization.",
      "Les nouvelles transitions peuvent augmenter; le resultat reste un AFN et peut exiger une determinisation.",
      "Neue Uebergaenge koennen zunehmen; das Ergebnis bleibt ein NEA und kann weiter determinisiert werden.",
      "Las nuevas transiciones pueden aumentar; el resultado sigue siendo AFN y puede requerir determinizar.",
      "As novas transicoes podem aumentar; o resultado continua AFN e pode exigir determinizacao.",
    ),
    example: l(
      "Se q epsilon-raggiunge f e f ha un arco a verso r, q riceve un arco a verso E(r); q diventa finale se f lo era.",
      "If q epsilon-reaches f and f has an a arc to r, q receives an a arc to E(r); q becomes final if f was.",
      "Si q atteint f par epsilon et f a un arc a vers r, q recoit a vers E(r); q devient final si f l'etait.",
      "Erreicht q per Epsilon f und hat f eine a-Kante nach r, erhaelt q eine a-Kante nach E(r); q wird gegebenenfalls final.",
      "Si q alcanza f por epsilon y f tiene arco a a r, q recibe a a E(r); q es final si f lo era.",
      "Se q alcanca f por epsilon e f tem arco a para r, q recebe a para E(r); q torna-se final se f era.",
    ),
  },
  remove_unreachable: {
    definition: l(
      "Riduce un automa alla sua parte raggiungibile dallo stato iniziale.",
      "Reduces an automaton to the part reachable from its initial state.",
      "Reduit un automate a la partie atteignable depuis son etat initial.",
      "Reduziert einen Automaten auf den vom Startzustand erreichbaren Teil.",
      "Reduce un automata a la parte alcanzable desde su estado inicial.",
      "Reduz um automato a parte alcancavel a partir do estado inicial.",
    ),
    notation: l(
      "Reach e il minimo insieme con q0 in Reach e delta(q,a) incluso quando q e in Reach.",
      "Reach is the least set with q0 in Reach and delta(q,a) included whenever q is in Reach.",
      "Reach est le plus petit ensemble avec q0 dans Reach et delta(q,a) inclus si q est dans Reach.",
      "Reach ist die kleinste Menge mit q0 und allen delta(q,a) fuer q in Reach.",
      "Reach es el menor conjunto con q0 y delta(q,a) si q esta en Reach.",
      "Reach e o menor conjunto com q0 e delta(q,a) quando q esta em Reach.",
    ),
    prerequisites: l(
      "Il modello deve avere uno stato iniziale; funziona su DFA e NFA.",
      "The model must have an initial state; it works on DFAs and NFAs.",
      "Le modele doit avoir un etat initial; il fonctionne sur AFD et AFN.",
      "Das Modell braucht einen Startzustand; es funktioniert fuer DEA und NEA.",
      "El modelo debe tener estado inicial; funciona en AFD y AFN.",
      "O modelo deve ter estado inicial; funciona em AFD e AFN.",
    ),
    procedure: procedure(
      l(
        "Avvia una visita in ampiezza o profondita da q0.",
        "Start a breadth-first or depth-first traversal from q0.",
        "Lancez un parcours largeur ou profondeur depuis q0.",
        "Starte eine Breiten- oder Tiefensuche bei q0.",
        "Inicia un recorrido en anchura o profundidad desde q0.",
        "Inicie uma busca em largura ou profundidade a partir de q0.",
      ),
      l(
        "Segui ogni transizione e marca le destinazioni non ancora viste.",
        "Follow every transition and mark destinations not yet seen.",
        "Suivez chaque transition et marquez les destinations non vues.",
        "Folge jeder Transition und markiere noch nicht besuchte Ziele.",
        "Sigue cada transicion y marca destinos aun no vistos.",
        "Siga cada transicao e marque destinos ainda nao vistos.",
      ),
      l(
        "Conserva stati e transizioni indotti dai marcati, eliminando il resto.",
        "Keep the states and transitions induced by marked states, removing the rest.",
        "Conservez etats et transitions induits par les marques, retirez le reste.",
        "Behalte die markierten Zustaende und ihre Kanten, entferne den Rest.",
        "Conserva estados y transiciones inducidos por marcados, elimina el resto.",
        "Mantenha estados e transicoes induzidos pelos marcados, removendo o restante.",
      ),
    ),
    interpretation: l(
      "Il linguaggio e identico: uno stato non raggiunto non puo apparire in una computazione da q0.",
      "The language is identical: an unreached state cannot occur in a computation from q0.",
      "Le langage est identique: un etat non atteint ne peut apparaitre dans un calcul depuis q0.",
      "Die Sprache ist identisch: ein unerreichter Zustand kann in keiner Berechnung von q0 vorkommen.",
      "El lenguaje es identico: un estado no alcanzado no puede aparecer en un computo desde q0.",
      "A linguagem e identica: um estado nao alcancado nao pode ocorrer num calculo a partir de q0.",
    ),
    limits: l(
      "La visita costa O(|Q|+|delta|). Non rimuove stati non produttivi ma raggiungibili.",
      "Traversal costs O(|Q|+|delta|). It does not remove reachable but non-productive states.",
      "Le parcours coute O(|Q|+|delta|). Il ne retire pas les etats atteignables mais non productifs.",
      "Die Suche kostet O(|Q|+|delta|). Sie entfernt keine erreichbaren, aber unproduktiven Zustaende.",
      "El recorrido cuesta O(|Q|+|delta|). No elimina estados alcanzables pero no productivos.",
      "A busca custa O(|Q|+|delta|). Nao remove estados alcancaveis mas nao produtivos.",
    ),
    example: l(
      "Se q3 e collegato solo a se stesso e non esiste un cammino q0 verso q3, q3 e il suo ciclo spariscono.",
      "If q3 only links to itself and no path from q0 reaches q3, q3 and its loop disappear.",
      "Si q3 ne relie que lui-meme et aucun chemin depuis q0 ne l'atteint, q3 et sa boucle disparaissent.",
      "Wenn q3 nur sich selbst erreicht und kein Weg von q0 nach q3 fuehrt, verschwinden q3 und seine Schleife.",
      "Si q3 solo se enlaza a si mismo y no hay camino desde q0, q3 y su ciclo desaparecen.",
      "Se q3 so liga a si proprio e nenhum caminho de q0 o alcanca, q3 e seu ciclo desaparecem.",
    ),
  },
  dfa_equivalence: {
    definition: l(
      "Decide se due DFA riconoscono lo stesso linguaggio esplorando il loro prodotto.",
      "Decides whether two DFAs recognize the same language by exploring their product.",
      "Decide si deux AFD reconnaissent le meme langage en explorant leur produit.",
      "Entscheidet durch Exploration des Produkts, ob zwei DEA dieselbe Sprache erkennen.",
      "Decide si dos AFD reconocen el mismo lenguaje explorando su producto.",
      "Decide se dois AFD reconhecem a mesma linguagem explorando o seu produto.",
    ),
    notation: l(
      "Il prodotto ha coppie (p,q). Una coppia e distinguente quando esattamente uno tra p e q e finale.",
      "The product has pairs (p,q). A pair is distinguishing when exactly one of p and q is accepting.",
      "Le produit a des paires (p,q). Une paire distingue si exactement l'un de p et q est final.",
      "Das Produkt hat Paare (p,q). Ein Paar unterscheidet, wenn genau einer von p und q akzeptierend ist.",
      "El producto tiene pares (p,q). Un par distingue si exactamente uno de p y q es final.",
      "O produto tem pares (p,q). Um par distingue se exatamente um de p e q e final.",
    ),
    prerequisites: l(
      "Servono due DFA sullo stesso alfabeto; le transizioni mancanti sono completate semanticamente con un pozzo.",
      "Two DFAs over the same alphabet are needed; missing transitions are semantically completed with a sink.",
      "Deux AFD sur le meme alphabet sont necessaires; les transitions manquantes sont completees par un puits.",
      "Zwei DEA ueber demselben Alphabet werden benoetigt; fehlende Uebergaenge werden mit einem Sinkzustand ergaenzt.",
      "Se necesitan dos AFD sobre el mismo alfabeto; transiciones ausentes se completan con pozo.",
      "Sao necessarios dois AFD sobre o mesmo alfabeto; transicoes ausentes sao completadas com sumidouro.",
    ),
    procedure: procedure(
      l(
        "Inizia dalla coppia degli stati iniziali e registra la parola vuota.",
        "Start with the pair of initial states and record the empty word.",
        "Commencez par la paire initiale et enregistrez le mot vide.",
        "Beginne mit dem Paar der Startzustaende und speichere das leere Wort.",
        "Empieza con el par de iniciales y registra la palabra vacia.",
        "Comece pelo par de iniciais e registe a palavra vazia.",
      ),
      l(
        "Visita in ampiezza le coppie ottenute applicando lo stesso simbolo a entrambi i lati.",
        "Breadth-first visit pairs obtained by applying the same symbol to both sides.",
        "Parcourez en largeur les paires obtenues en appliquant le meme symbole aux deux cotes.",
        "Durchsuche breit die Paare, die entstehen, wenn dasselbe Zeichen auf beide Seiten angewandt wird.",
        "Recorre en anchura pares obtenidos al aplicar el mismo simbolo en ambos lados.",
        "Visite em largura pares obtidos aplicando o mesmo simbolo aos dois lados.",
      ),
      l(
        "Fermati alla prima coppia distinguente oppure quando tutte le coppie raggiungibili sono state visitate.",
        "Stop at the first distinguishing pair or once all reachable pairs have been visited.",
        "Arretez a la premiere paire distinguante ou apres toutes les paires atteignables.",
        "Halte beim ersten unterscheidenden Paar oder wenn alle erreichbaren Paare besucht sind.",
        "Detente en el primer par distintivo o al visitar todos los pares alcanzables.",
        "Pare no primeiro par distintivo ou quando todos os pares alcancaveis forem visitados.",
      ),
    ),
    interpretation: l(
      "Una coppia distinguente produce un controesempio minimo; se non esiste, i linguaggi sono uguali.",
      "A distinguishing pair produces a shortest counterexample; if none exists, the languages are equal.",
      "Une paire distinguante produit un contre-exemple minimal; sinon les langages sont egaux.",
      "Ein unterscheidendes Paar liefert ein kuerzestes Gegenbeispiel; ohne eines sind die Sprachen gleich.",
      "Un par distintivo produce un contraejemplo mas corto; si no existe, los lenguajes son iguales.",
      "Um par distintivo produz um contraexemplo mais curto; se nao existe, as linguagens sao iguais.",
    ),
    limits: l(
      "La visita costa al piu O(|Q1| |Q2| |Sigma|); il controesempio minimo dipende dall'ordine dell'alfabeto visualizzato.",
      "Traversal costs at most O(|Q1| |Q2| |Sigma|); the shortest witness depends on the displayed alphabet order.",
      "Le parcours coute au plus O(|Q1| |Q2| |Sigma|); le temoin minimal depend de l'ordre d'alphabet affiche.",
      "Die Suche kostet hoechstens O(|Q1| |Q2| |Sigma|); das kuerzeste Zeugnis haengt von der Alphabetreihenfolge ab.",
      "El recorrido cuesta como maximo O(|Q1| |Q2| |Sigma|); el testigo minimo depende del orden mostrado.",
      "A busca custa no maximo O(|Q1| |Q2| |Sigma|); a testemunha minima depende da ordem do alfabeto mostrado.",
    ),
    example: l(
      "Se dopo a una macchina e finale e l'altra no, a e un controesempio e i DFA non sono equivalenti.",
      "If after a one machine is accepting and the other is not, a is a counterexample and the DFAs are inequivalent.",
      "Si apres a une machine est finale et l'autre non, a est un contre-exemple et les AFD ne sont pas equivalents.",
      "Ist nach a eine Maschine akzeptierend und die andere nicht, ist a ein Gegenbeispiel.",
      "Si tras a una maquina es final y la otra no, a es contraejemplo y los AFD no son equivalentes.",
      "Se apos a uma maquina e final e a outra nao, a e contraexemplo e os AFD nao sao equivalentes.",
    ),
  },
  regular_grammar_to_nfa: {
    definition: l(
      "Traduce una grammatica regolare lineare destra in un NFA equivalente.",
      "Translates a right-linear regular grammar into an equivalent NFA.",
      "Traduit une grammaire reguliere lineaire droite en AFN equivalent.",
      "Uebersetzt eine rechtslineare regulaere Grammatik in einen aequivalenten NEA.",
      "Traduce una gramatica regular lineal derecha en un AFN equivalente.",
      "Traduz uma gramatica regular linear a direita num AFN equivalente.",
    ),
    notation: l(
      "Ogni variabile A e uno stato. A -> aB diventa A -a-> B; A -> a porta a un nuovo finale.",
      "Every variable A is a state. A -> aB becomes A -a-> B; A -> a goes to a fresh final.",
      "Chaque variable A est un etat. A -> aB devient A -a-> B; A -> a va vers un final nouveau.",
      "Jede Variable A ist ein Zustand. A -> aB wird A -a-> B; A -> a fuehrt zu einem neuen Endzustand.",
      "Cada variable A es un estado. A -> aB se vuelve A -a-> B; A -> a llega a un final nuevo.",
      "Cada variavel A e um estado. A -> aB torna-se A -a-> B; A -> a vai para um final novo.",
    ),
    prerequisites: l(
      "Le produzioni devono essere lineari destre: al massimo una variabile, in ultima posizione.",
      "Productions must be right-linear: at most one variable, in final position.",
      "Les productions doivent etre lineaires droites: au plus une variable, en derniere position.",
      "Produktionen muessen rechtslinear sein: hoechstens eine Variable an letzter Stelle.",
      "Las producciones deben ser lineales derechas: como mucho una variable al final.",
      "As producoes devem ser lineares a direita: no maximo uma variavel na ultima posicao.",
    ),
    procedure: procedure(
      l(
        "Crea uno stato per ciascuna variabile e usa il simbolo iniziale come stato iniziale.",
        "Create one state for each variable and use the start symbol as initial state.",
        "Creez un etat par variable et utilisez le symbole initial comme etat initial.",
        "Erzeuge einen Zustand je Variable und nutze das Startsymbol als Startzustand.",
        "Crea un estado por variable y usa el simbolo inicial como estado inicial.",
        "Crie um estado por variavel e use o simbolo inicial como estado inicial.",
      ),
      l(
        "Trasforma ogni regola A -> aB in un arco etichettato a da A a B.",
        "Turn every A -> aB rule into an a-labeled arc from A to B.",
        "Transformez chaque regle A -> aB en arc a de A vers B.",
        "Wandle jede Regel A -> aB in eine a-Kante von A nach B um.",
        "Transforma cada regla A -> aB en arco a de A a B.",
        "Transforme cada regra A -> aB num arco a de A para B.",
      ),
      l(
        "Aggiungi un finale comune per regole solo terminali e rendi iniziale finale se S -> epsilon.",
        "Add one shared final for terminal-only rules and make start accepting if S -> epsilon.",
        "Ajoutez un final commun pour les regles terminales et rendez le debut final si S -> epsilon.",
        "Fuege einen gemeinsamen Endzustand fuer reine Terminalregeln hinzu und mache den Start bei S -> epsilon final.",
        "Anade un final comun para reglas terminales y haz inicial final si S -> epsilon.",
        "Adicione um final comum para regras terminais e torne o inicial final se S -> epsilon.",
      ),
    ),
    interpretation: l(
      "Le derivazioni della grammatica corrispondono uno a uno ai cammini dell'NFA che consumano gli stessi terminali.",
      "Grammar derivations correspond one-for-one to NFA paths consuming the same terminals.",
      "Les derivations grammaticales correspondent aux chemins AFN consommant les memes terminaux.",
      "Grammatikableitungen entsprechen genau NEA-Pfaden mit denselben Terminalen.",
      "Las derivaciones gramaticales corresponden a caminos AFN que consumen los mismos terminales.",
      "As derivacoes da gramatica correspondem a caminhos AFN que consomem os mesmos terminais.",
    ),
    limits: l(
      "Non accetta CFG arbitrarie o produzioni lineari sinistre. Il risultato puo essere non deterministico.",
      "It does not accept arbitrary CFGs or left-linear productions. The result may be nondeterministic.",
      "Il n'accepte ni CFG arbitraires ni productions lineaires gauches. Le resultat peut etre non deterministe.",
      "Es akzeptiert keine beliebigen CFG oder linkslinearen Produktionen. Das Ergebnis kann nichtdeterministisch sein.",
      "No admite CFG arbitrarias ni producciones lineales izquierdas. El resultado puede ser no determinista.",
      "Nao aceita CFG arbitrarias nem producoes lineares a esquerda. O resultado pode ser nao deterministico.",
    ),
    example: l(
      "S -> aS | b diventa un ciclo a su S e un arco b da S al nuovo finale.",
      "S -> aS | b becomes an a loop on S and a b arc from S to the new final.",
      "S -> aS | b devient une boucle a sur S et un arc b vers le nouveau final.",
      "S -> aS | b wird zu einer a-Schleife auf S und einer b-Kante zum neuen Ende.",
      "S -> aS | b se vuelve ciclo a en S y arco b al nuevo final.",
      "S -> aS | b torna-se ciclo a em S e arco b para o novo final.",
    ),
  },
  cfg_to_pda: {
    definition: l(
      "Costruisce un PDA non deterministico che accetta lo stesso linguaggio di una grammatica context-free.",
      "Builds a nondeterministic PDA accepting the same language as a context-free grammar.",
      "Construit un PDA non deterministe acceptant le meme langage qu'une grammaire context-free.",
      "Konstruiert einen nichtdeterministischen PDA, der dieselbe Sprache wie eine kontextfreie Grammatik akzeptiert.",
      "Construye un PDA no determinista que acepta el mismo lenguaje que una gramatica libre de contexto.",
      "Constroi um PDA nao deterministico que aceita a mesma linguagem de uma gramatica livre de contexto.",
    ),
    notation: l(
      "La pila contiene la forma sentenziale da verificare. Una regola A -> alpha sostituisce A con alpha sulla pila.",
      "The stack holds the sentential form to verify. A rule A -> alpha replaces A with alpha on the stack.",
      "La pile contient la forme a verifier. Une regle A -> alpha remplace A par alpha sur la pile.",
      "Der Keller enthaelt die zu pruefende Satzform. A -> alpha ersetzt A durch alpha auf dem Keller.",
      "La pila contiene la forma a verificar. A -> alpha sustituye A por alpha en la pila.",
      "A pilha contem a forma sentencial a verificar. A -> alpha substitui A por alpha na pilha.",
    ),
    prerequisites: l(
      "Serve una CFG con simbolo iniziale; il PDA usa il non determinismo per scegliere le produzioni.",
      "A CFG with a start symbol is required; the PDA uses nondeterminism to choose productions.",
      "Une CFG avec symbole initial est requise; le PDA utilise le non-determinisme pour choisir les regles.",
      "Eine CFG mit Startsymbol ist erforderlich; der PDA nutzt Nichtdeterminismus zur Regelauswahl.",
      "Se requiere una CFG con simbolo inicial; el PDA usa no determinismo para elegir producciones.",
      "E necessaria uma CFG com simbolo inicial; o PDA usa nao determinismo para escolher producoes.",
    ),
    procedure: procedure(
      l(
        "Inizializza la pila con il simbolo iniziale della grammatica.",
        "Initialize the stack with the grammar start symbol.",
        "Initialisez la pile avec le symbole initial de la grammaire.",
        "Initialisiere den Keller mit dem Startsymbol der Grammatik.",
        "Inicializa la pila con el simbolo inicial de la gramatica.",
        "Inicialize a pilha com o simbolo inicial da gramatica.",
      ),
      l(
        "Per A in cima, scegli non deterministicamente A -> alpha e sostituisci A con alpha al contrario.",
        "For top A, nondeterministically choose A -> alpha and replace A by reversed alpha.",
        "Pour A au sommet, choisissez A -> alpha et remplacez A par alpha inverse.",
        "Waehle fuer oberstes A nichtdeterministisch A -> alpha und ersetze A durch umgekehrtes alpha.",
        "Para A arriba, elige A -> alpha y sustituye A por alpha invertido.",
        "Para A no topo, escolha A -> alpha e substitua A por alpha invertido.",
      ),
      l(
        "Per un terminale a in cima, leggi a dall'input e rimuovilo; accetta a input e pila vuoti.",
        "For top terminal a, read a from input and pop it; accept with empty input and stack.",
        "Pour un terminal a au sommet, lisez a et depilez; acceptez avec entree et pile vides.",
        "Lies bei oberstem Terminal a das Eingabe-a und entferne es; akzeptiere bei leerer Eingabe und leerem Keller.",
        "Para terminal a arriba, lee a y desapila; acepta con entrada y pila vacias.",
        "Para terminal a no topo, leia a e remova-o; aceite com entrada e pilha vazias.",
      ),
    ),
    interpretation: l(
      "Un cammino accettante corrisponde a una derivazione della parola nella CFG, e viceversa.",
      "An accepting path corresponds to a CFG derivation of the word, and conversely.",
      "Un chemin acceptant correspond a une derivation CFG du mot, et reciproquement.",
      "Ein akzeptierender Pfad entspricht einer CFG-Ableitung des Wortes und umgekehrt.",
      "Un camino aceptante corresponde a una derivacion CFG de la palabra, y viceversa.",
      "Um caminho aceitante corresponde a uma derivacao CFG da palavra, e vice-versa.",
    ),
    limits: l(
      "Il PDA generato e non deterministico. Non e un algoritmo di decisione per l'appartenenza senza cercare i cammini.",
      "The generated PDA is nondeterministic. It is not a membership decision algorithm without searching paths.",
      "Le PDA produit est non deterministe. Ce n'est pas une decision d'appartenance sans rechercher les chemins.",
      "Der erzeugte PDA ist nichtdeterministisch. Ohne Pfadsuche ist dies kein Entscheidungsalgorithmus fuer Zugehoerigkeit.",
      "El PDA generado es no determinista. No decide pertenencia sin buscar caminos.",
      "O PDA gerado e nao deterministico. Nao decide pertinencia sem procurar caminhos.",
    ),
    example: l(
      "Con S -> aSb | epsilon, la pila espande S in bSa, poi confronta a e b nell'ordine dell'input.",
      "With S -> aSb | epsilon, the stack expands S to bSa, then matches a and b in input order.",
      "Avec S -> aSb | epsilon, la pile developpe S en bSa, puis compare a et b dans l'ordre d'entree.",
      "Bei S -> aSb | epsilon erweitert der Keller S zu bSa und vergleicht dann a und b in Eingabereihenfolge.",
      "Con S -> aSb | epsilon, la pila expande S a bSa y compara a y b en orden de entrada.",
      "Com S -> aSb | epsilon, a pilha expande S para bSa e depois compara a e b na ordem da entrada.",
    ),
  },
  chomsky_normal_form: {
    definition: l(
      "Porta una CFG in forma normale di Chomsky, dove le regole sono A -> BC o A -> a, con l'eccezione controllata per epsilon.",
      "Puts a CFG into Chomsky normal form, where rules are A -> BC or A -> a, with the controlled epsilon exception.",
      "Met une CFG en forme normale de Chomsky: A -> BC ou A -> a, avec l'exception epsilon controlee.",
      "Bringt eine CFG in Chomsky-Normalform: A -> BC oder A -> a, mit kontrollierter Epsilon-Ausnahme.",
      "Lleva una CFG a forma normal de Chomsky: A -> BC o A -> a, con excepcion epsilon controlada.",
      "Coloca uma CFG em forma normal de Chomsky: A -> BC ou A -> a, com excecao epsilon controlada.",
    ),
    notation: l(
      "Le variabili generano due variabili o un solo terminale. Un nuovo S0 protegge il simbolo iniziale originale.",
      "Variables derive two variables or one terminal. A fresh S0 protects the original start symbol.",
      "Les variables produisent deux variables ou un terminal. Un nouveau S0 protege le depart original.",
      "Variablen erzeugen zwei Variablen oder ein Terminal. Ein neues S0 schuetzt das alte Startsymbol.",
      "Las variables producen dos variables o un terminal. Un S0 nuevo protege el inicial original.",
      "Variaveis geram duas variaveis ou um terminal. Um novo S0 protege o inicial original.",
    ),
    prerequisites: l(
      "Serve una CFG finita; la normalizzazione preserva il linguaggio, salvo il trattamento esplicito della parola vuota.",
      "A finite CFG is required; normalization preserves the language, subject to explicit empty-word handling.",
      "Une CFG finie est requise; la normalisation preserve le langage, avec traitement explicite du mot vide.",
      "Eine endliche CFG ist erforderlich; die Normalisierung erhaelt die Sprache mit expliziter Behandlung des leeren Wortes.",
      "Se requiere una CFG finita; la normalizacion preserva el lenguaje con manejo explicito de palabra vacia.",
      "E necessaria uma CFG finita; a normalizacao preserva a linguagem com tratamento explicito da palavra vazia.",
    ),
    procedure: procedure(
      l(
        "Aggiungi S0 -> S e individua simboli annullabili, poi elimina le produzioni epsilon non necessarie.",
        "Add S0 -> S and find nullable symbols, then remove unnecessary epsilon productions.",
        "Ajoutez S0 -> S et trouvez les symboles annulables, puis retirez les epsilon inutiles.",
        "Fuege S0 -> S hinzu, finde nullable Symbole und entferne unnoetige Epsilon-Produktionen.",
        "Anade S0 -> S e identifica anulables, luego elimina epsilon innecesarios.",
        "Adicione S0 -> S e encontre simbolos anulaveis, depois remova epsilons desnecessarios.",
      ),
      l(
        "Elimina produzioni unitarie e simboli inutili o irraggiungibili.",
        "Remove unit productions and useless or unreachable symbols.",
        "Retirez les productions unitaires et les symboles inutiles ou inaccessibles.",
        "Entferne Einheitsproduktionen und nutzlose oder unerreichbare Symbole.",
        "Elimina producciones unitarias y simbolos inutiles o inalcanzables.",
        "Remova producoes unitarias e simbolos inuteis ou inacessiveis.",
      ),
      l(
        "Sostituisci terminali in regole lunghe e binarizza ogni parte destra di lunghezza maggiore di due.",
        "Replace terminals in long rules and binarize every right side longer than two.",
        "Remplacez les terminaux dans les longues regles et binarisez toute partie droite de longueur superieure a deux.",
        "Ersetze Terminals in langen Regeln und binarisiere jede rechte Seite laenger als zwei.",
        "Sustituye terminales en reglas largas y binariza cada lado derecho de longitud mayor que dos.",
        "Substitua terminais em regras longas e binarize cada lado direito com mais de dois simbolos.",
      ),
    ),
    interpretation: l(
      "Il risultato e una grammatica equivalente adatta a CYK e ad altri algoritmi tabellari.",
      "The result is an equivalent grammar suited to CYK and other table-driven algorithms.",
      "Le resultat est une grammaire equivalente adaptee a CYK et autres algorithmes tabulaires.",
      "Das Ergebnis ist eine aequivalente Grammatik fuer CYK und andere Tabellenalgorithmen.",
      "El resultado es una gramatica equivalente apta para CYK y otros algoritmos tabulares.",
      "O resultado e uma gramatica equivalente adequada a CYK e outros algoritmos tabulares.",
    ),
    limits: l(
      "La grammatica puo crescere sensibilmente. Non conserva la forma o l'ambiguita delle derivazioni originali.",
      "The grammar can grow substantially. It does not preserve original derivation shape or ambiguity.",
      "La grammaire peut beaucoup croitre. Elle ne preserve ni la forme ni l'ambiguite des derivations originales.",
      "Die Grammatik kann deutlich wachsen. Form und Mehrdeutigkeit alter Ableitungen bleiben nicht erhalten.",
      "La gramatica puede crecer mucho. No conserva forma ni ambiguedad de derivaciones originales.",
      "A gramatica pode crescer bastante. Nao preserva forma nem ambiguidade das derivacoes originais.",
    ),
    example: l(
      "A -> aBC diventa A -> X_a D e D -> BC, con X_a -> a.",
      "A -> aBC becomes A -> X_a D and D -> BC, with X_a -> a.",
      "A -> aBC devient A -> X_a D et D -> BC, avec X_a -> a.",
      "A -> aBC wird zu A -> X_a D und D -> BC, mit X_a -> a.",
      "A -> aBC se vuelve A -> X_a D y D -> BC, con X_a -> a.",
      "A -> aBC torna-se A -> X_a D e D -> BC, com X_a -> a.",
    ),
  },
  cyk: {
    definition: l(
      "Decide l'appartenenza di una parola a una CFG in forma normale di Chomsky tramite programmazione dinamica.",
      "Decides whether a word belongs to a CNF CFG through dynamic programming.",
      "Decide l'appartenance d'un mot a une CFG en forme de Chomsky par programmation dynamique.",
      "Entscheidet die Wortzugehoerigkeit zu einer CNF-Grammatik durch dynamische Programmierung.",
      "Decide si una palabra pertenece a una CFG en forma de Chomsky mediante programacion dinamica.",
      "Decide se uma palavra pertence a uma CFG em forma normal de Chomsky por programacao dinamica.",
    ),
    notation: l(
      "T[i,j] contiene le variabili che generano la sottostringa dalla posizione i di lunghezza j.",
      "T[i,j] contains variables deriving the substring at position i of length j.",
      "T[i,j] contient les variables derivant la sous-chaine de position i et longueur j.",
      "T[i,j] enthaelt Variablen, die das Teilwort bei i der Laenge j erzeugen.",
      "T[i,j] contiene variables que generan la subcadena en i de longitud j.",
      "T[i,j] contem variaveis que geram a subcadeia em i de comprimento j.",
    ),
    prerequisites: l(
      "La grammatica deve essere in CNF; per la parola vuota serve gestire separatamente S -> epsilon.",
      "The grammar must be in CNF; the empty word requires separate S -> epsilon handling.",
      "La grammaire doit etre en CNF; le mot vide demande un traitement separe de S -> epsilon.",
      "Die Grammatik muss in CNF sein; das leere Wort erfordert eine separate S -> epsilon-Behandlung.",
      "La gramatica debe estar en CNF; palabra vacia requiere manejar S -> epsilon aparte.",
      "A gramatica deve estar em CNF; palavra vazia requer tratar S -> epsilon separadamente.",
    ),
    procedure: procedure(
      l(
        "Riempi la diagonale: inserisci A in T[i,1] quando A -> w[i].",
        "Fill the diagonal: place A in T[i,1] when A -> w[i].",
        "Remplissez la diagonale: mettez A dans T[i,1] si A -> w[i].",
        "Fuelle die Diagonale: setze A in T[i,1], wenn A -> w[i].",
        "Llena la diagonal: inserta A en T[i,1] si A -> w[i].",
        "Preencha a diagonal: insira A em T[i,1] quando A -> w[i].",
      ),
      l(
        "Per lunghezze crescenti, prova ogni divisione della sottostringa e ogni regola A -> BC.",
        "For increasing lengths, try every split of the substring and every A -> BC rule.",
        "Pour des longueurs croissantes, essayez chaque coupe et chaque regle A -> BC.",
        "Probiere fuer wachsende Laengen jede Teilung und jede Regel A -> BC.",
        "Para longitudes crecientes, prueba cada division y cada regla A -> BC.",
        "Para comprimentos crescentes, tente cada divisao e cada regra A -> BC.",
      ),
      l(
        "Accetta se il simbolo iniziale compare in T[0,n].",
        "Accept if the start symbol appears in T[0,n].",
        "Acceptez si le symbole initial apparait dans T[0,n].",
        "Akzeptiere, wenn das Startsymbol in T[0,n] erscheint.",
        "Acepta si el simbolo inicial aparece en T[0,n].",
        "Aceite se o simbolo inicial aparece em T[0,n].",
      ),
    ),
    interpretation: l(
      "La tabella mostra quali variabili spiegano ogni sottostringa; la cella finale giustifica accettazione o rifiuto.",
      "The table shows which variables explain every substring; the final cell justifies acceptance or rejection.",
      "La table montre quelles variables expliquent chaque sous-chaine; la cellule finale justifie l'acceptation ou le rejet.",
      "Die Tabelle zeigt Variablen fuer jedes Teilwort; die letzte Zelle begruendet Annahme oder Ablehnung.",
      "La tabla muestra variables para cada subcadena; la celda final justifica aceptar o rechazar.",
      "A tabela mostra variaveis para cada subcadeia; a celula final justifica aceitar ou rejeitar.",
    ),
    limits: l(
      "Tempo O(n^3 |P|) e spazio O(n^2 |V|). CYK richiede CNF e non risolve l'ambiguita da solo.",
      "Time O(n^3 |P|) and space O(n^2 |V|). CYK requires CNF and does not resolve ambiguity alone.",
      "Temps O(n^3 |P|), espace O(n^2 |V|). CYK exige CNF et ne resout pas seul l'ambiguite.",
      "Zeit O(n^3 |P|), Platz O(n^2 |V|). CYK verlangt CNF und loest Mehrdeutigkeit nicht allein.",
      "Tiempo O(n^3 |P|) y espacio O(n^2 |V|). CYK requiere CNF y no resuelve ambiguedad solo.",
      "Tempo O(n^3 |P|) e espaco O(n^2 |V|). CYK exige CNF e nao resolve ambiguidade sozinho.",
    ),
    example: l(
      "Con S -> AB, A -> a, B -> b, per ab la diagonale e {A},{B} e T[0,2] contiene S.",
      "With S -> AB, A -> a, B -> b, for ab the diagonal is {A},{B} and T[0,2] contains S.",
      "Avec S -> AB, A -> a, B -> b, pour ab la diagonale est {A},{B} et T[0,2] contient S.",
      "Bei S -> AB, A -> a, B -> b ist fuer ab die Diagonale {A},{B} und T[0,2] enthaelt S.",
      "Con S -> AB, A -> a, B -> b, para ab la diagonal es {A},{B} y T[0,2] contiene S.",
      "Com S -> AB, A -> a, B -> b, para ab a diagonal e {A},{B} e T[0,2] contem S.",
    ),
  },
  ll1_analysis: {
    definition: l(
      "Calcola FIRST, FOLLOW e la tabella predittiva per verificare se una CFG e analizzabile LL(1).",
      "Computes FIRST, FOLLOW, and the predictive table to check whether a CFG is LL(1)-parsable.",
      "Calcule FIRST, FOLLOW et la table predictive pour verifier si une CFG est analysable LL(1).",
      "Berechnet FIRST, FOLLOW und die Vorhersagetabelle, um eine CFG auf LL(1)-Analysierbarkeit zu pruefen.",
      "Calcula FIRST, FOLLOW y la tabla predictiva para comprobar si una CFG es analizable LL(1).",
      "Calcula FIRST, FOLLOW e a tabela preditiva para verificar se uma CFG e analisavel LL(1).",
    ),
    notation: l(
      "FIRST(alpha) sono i terminali iniziali possibili; FOLLOW(A) sono i terminali che possono seguire A. epsilon e $ sono marcatori speciali.",
      "FIRST(alpha) contains possible first terminals; FOLLOW(A) contains terminals that may follow A. epsilon and $ are special markers.",
      "FIRST(alpha) contient les terminaux initiaux possibles; FOLLOW(A) ceux pouvant suivre A. epsilon et $ sont speciaux.",
      "FIRST(alpha) sind moegliche erste Terminals; FOLLOW(A) sind moegliche Nachfolger. Epsilon und $ sind Sondermarker.",
      "FIRST(alpha) contiene terminales iniciales posibles; FOLLOW(A) los que pueden seguir A. epsilon y $ son especiales.",
      "FIRST(alpha) contem terminais iniciais possiveis; FOLLOW(A) terminais que podem seguir A. epsilon e $ sao especiais.",
    ),
    prerequisites: l(
      "Serve una CFG; ricorsione sinistra e prefissi comuni producono spesso conflitti e vanno rifattorizzati.",
      "A CFG is required; left recursion and common prefixes often produce conflicts and must be refactored.",
      "Une CFG est requise; recursion gauche et prefixes communs causent souvent des conflits a refactoriser.",
      "Eine CFG ist erforderlich; Linksrekursion und gemeinsame Praefixe verursachen oft Konflikte und muessen umgeformt werden.",
      "Se requiere una CFG; recursion izquierda y prefijos comunes suelen producir conflictos y deben refactorizarse.",
      "E necessaria uma CFG; recursao esquerda e prefixos comuns produzem conflitos e devem ser refatorados.",
    ),
    procedure: procedure(
      l(
        "Calcola FIRST fino a punto fisso, propagando epsilon attraverso le sequenze.",
        "Compute FIRST to a fixed point, propagating epsilon through sequences.",
        "Calculez FIRST jusqu'au point fixe en propageant epsilon dans les sequences.",
        "Berechne FIRST bis zum Fixpunkt und propagieren Epsilon durch Sequenzen.",
        "Calcula FIRST hasta punto fijo, propagando epsilon por secuencias.",
        "Calcule FIRST ate ponto fixo, propagando epsilon por sequencias.",
      ),
      l(
        "Inizializza FOLLOW(S) con $ e propaga i simboli di seguito per tutte le produzioni.",
        "Initialize FOLLOW(S) with $ and propagate following symbols through all productions.",
        "Initialisez FOLLOW(S) par $ et propagez les symboles suivants pour toutes les regles.",
        "Initialisiere FOLLOW(S) mit $ und propagiere Folgesymbole durch alle Produktionen.",
        "Inicializa FOLLOW(S) con $ y propaga simbolos siguientes por todas las producciones.",
        "Inicialize FOLLOW(S) com $ e propague simbolos seguintes por todas as producoes.",
      ),
      l(
        "Inserisci A -> alpha in M[A,a] per a in FIRST(alpha), e in FOLLOW(A) se epsilon e in FIRST(alpha).",
        "Put A -> alpha in M[A,a] for a in FIRST(alpha), and in FOLLOW(A) when epsilon is in FIRST(alpha).",
        "Placez A -> alpha dans M[A,a] pour a dans FIRST(alpha), et dans FOLLOW(A) si epsilon est dans FIRST(alpha).",
        "Setze A -> alpha in M[A,a] fuer a in FIRST(alpha), und in FOLLOW(A), falls epsilon in FIRST(alpha) liegt.",
        "Inserta A -> alpha en M[A,a] para a en FIRST(alpha), y en FOLLOW(A) si epsilon esta en FIRST(alpha).",
        "Insira A -> alpha em M[A,a] para a em FIRST(alpha), e em FOLLOW(A) se epsilon esta em FIRST(alpha).",
      ),
    ),
    interpretation: l(
      "La grammatica e LL(1) solo se ogni cella della tabella contiene al massimo una produzione; i conflitti spiegano dove la previsione e ambigua.",
      "A grammar is LL(1) only if every table cell has at most one production; conflicts show where prediction is ambiguous.",
      "Une grammaire est LL(1) seulement si chaque cellule contient au plus une production; les conflits montrent l'ambiguite.",
      "Eine Grammatik ist nur LL(1), wenn jede Tabellenzelle hoechstens eine Produktion hat; Konflikte zeigen mehrdeutige Vorhersagen.",
      "Una gramatica es LL(1) solo si cada celda tiene como mucho una produccion; conflictos muestran prediccion ambigua.",
      "Uma gramatica e LL(1) somente se cada celula tiver no maximo uma producao; conflitos mostram previsao ambigua.",
    ),
    limits: l(
      "LL(1) e una classe ristretta di CFG. L'assenza di conflitti dipende dalla grammatica, non solo dal linguaggio.",
      "LL(1) is a restricted CFG class. Absence of conflicts depends on the grammar, not only on the language.",
      "LL(1) est une classe restreinte de CFG. L'absence de conflits depend de la grammaire, pas seulement du langage.",
      "LL(1) ist eine eingeschraenkte CFG-Klasse. Konfliktfreiheit haengt von der Grammatik ab, nicht nur von der Sprache.",
      "LL(1) es una clase restringida de CFG. Ausencia de conflictos depende de la gramatica, no solo del lenguaje.",
      "LL(1) e uma classe restrita de CFG. A ausencia de conflitos depende da gramatica, nao apenas da linguagem.",
    ),
    example: l(
      "Per S -> aA | bB, FIRST(S)={a,b}; le due produzioni occupano celle diverse e non creano conflitto.",
      "For S -> aA | bB, FIRST(S)={a,b}; the two productions occupy different cells and do not conflict.",
      "Pour S -> aA | bB, FIRST(S)={a,b}; les deux regles occupent des cellules differentes sans conflit.",
      "Bei S -> aA | bB ist FIRST(S)={a,b}; die Regeln liegen in verschiedenen Zellen ohne Konflikt.",
      "Para S -> aA | bB, FIRST(S)={a,b}; las producciones ocupan celdas distintas sin conflicto.",
      "Para S -> aA | bB, FIRST(S)={a,b}; as producoes ocupam celulas distintas sem conflito.",
    ),
  },
  regular_pumping: {
    definition: l(
      "Organizza l'analisi del pumping lemma per linguaggi regolari; e uno strumento di confutazione, non un criterio completo di regolarita.",
      "Organizes the regular-language pumping lemma analysis; it is a refutation tool, not a complete regularity criterion.",
      "Organise l'analyse du lemme de pompage regulier; c'est un outil de refutation, pas un critere complet.",
      "Ordnet die Analyse des Pumping-Lemmas fuer regulaere Sprachen; es ist ein Widerlegungswerkzeug, kein vollstaendiges Kriterium.",
      "Organiza el analisis del lema de bombeo regular; es herramienta de refutacion, no criterio completo.",
      "Organiza a analise do lema do bombeamento regular; e ferramenta de refutacao, nao criterio completo.",
    ),
    notation: l(
      "Se L e regolare, esiste p tale che ogni w in L con |w|>=p ha w=xyz, |xy|<=p, |y|>0 e xy^iz in L per ogni i>=0.",
      "If L is regular, some p ensures every w in L with |w|>=p has w=xyz, |xy|<=p, |y|>0, and xy^iz in L for every i>=0.",
      "Si L est regulier, il existe p: tout w de longueur au moins p a w=xyz, |xy|<=p, |y|>0 et xy^iz dans L pour tout i>=0.",
      "Ist L regulaer, gibt es p: jedes w mit |w|>=p hat w=xyz, |xy|<=p, |y|>0 und xy^iz in L fuer jedes i>=0.",
      "Si L es regular, existe p: todo w con |w|>=p tiene w=xyz, |xy|<=p, |y|>0 y xy^iz en L para todo i>=0.",
      "Se L e regular, existe p: todo w com |w|>=p tem w=xyz, |xy|<=p, |y|>0 e xy^iz em L para todo i>=0.",
    ),
    prerequisites: l(
      "Fornisci una parola candidata di lunghezza almeno p e gli esponenti da ispezionare. La scelta di w fa parte della dimostrazione.",
      "Provide a candidate word of length at least p and exponents to inspect. Choosing w is part of the proof.",
      "Fournissez un mot candidat de longueur au moins p et les exposants a examiner. Le choix de w fait partie de la preuve.",
      "Gib ein Kandidatenwort der Laenge mindestens p und zu pruefende Exponenten an. Die Wahl von w ist Teil des Beweises.",
      "Proporciona palabra candidata de longitud al menos p y exponentes. Elegir w es parte de la prueba.",
      "Forneca palavra candidata de comprimento ao menos p e expoentes. Escolher w faz parte da prova.",
    ),
    procedure: procedure(
      l(
        "Assumi che L sia regolare e lascia p arbitrario, scelto dall'avversario.",
        "Assume L is regular and let p be arbitrary, chosen by the opponent.",
        "Supposez L regulier et laissez p arbitraire, choisi par l'adversaire.",
        "Nimm an, L sei regulaer, und lasse p beliebig vom Gegner waehlen.",
        "Supone L regular y deja p arbitrario, elegido por el adversario.",
        "Suponha L regular e deixe p arbitrario, escolhido pelo oponente.",
      ),
      l(
        "Scegli w in L con |w|>=p e considera ogni decomposizione xyz che soddisfa i vincoli.",
        "Choose w in L with |w|>=p and consider every xyz split satisfying the constraints.",
        "Choisissez w dans L avec |w|>=p et chaque decomposition xyz conforme aux contraintes.",
        "Waehle w in L mit |w|>=p und betrachte jede zulaessige xyz-Zerlegung.",
        "Elige w en L con |w|>=p y considera cada division xyz que cumple las restricciones.",
        "Escolha w em L com |w|>=p e considere cada decomposicao xyz que satisfaz as restricoes.",
      ),
      l(
        "Trova un i per cui xy^iz non e in L in ogni caso; allora l'assunzione di regolarita e falsa.",
        "Find an i with xy^iz not in L in every case; then the regularity assumption is false.",
        "Trouvez un i tel que xy^iz ne soit pas dans L dans chaque cas; alors l'hypothese est fausse.",
        "Finde in jedem Fall ein i mit xy^iz nicht in L; dann ist die Regularitaetsannahme falsch.",
        "Encuentra un i con xy^iz fuera de L en cada caso; entonces la suposicion es falsa.",
        "Encontre um i com xy^iz fora de L em cada caso; entao a suposicao e falsa.",
      ),
    ),
    interpretation: l(
      "Le decomposizioni enumerate mostrano tutti i casi che una prova deve coprire. Un singolo pompaggio riuscito non prova regolarita.",
      "Enumerated decompositions show all cases a proof must cover. One successful pumping does not prove regularity.",
      "Les decompositions enumerees montrent tous les cas qu'une preuve doit couvrir. Un pompage reussi ne prouve pas la regularite.",
      "Die aufgelisteten Zerlegungen zeigen alle Faelle, die ein Beweis abdecken muss. Ein gelungenes Pumpen beweist keine Regularitaet.",
      "Las descomposiciones enumeradas muestran todos los casos de prueba. Un bombeo exitoso no prueba regularidad.",
      "As decomposicoes enumeradas mostram todos os casos da prova. Um bombeamento bem-sucedido nao prova regularidade.",
    ),
    limits: l(
      "Il lemma e necessario ma non sufficiente. L'interfaccia limita parola, esponenti e decomposizioni per mantenere il calcolo finito.",
      "The lemma is necessary but not sufficient. The interface bounds word, exponents, and decompositions to keep computation finite.",
      "Le lemme est necessaire mais non suffisant. L'interface borne mot, exposants et decompositions pour garder un calcul fini.",
      "Das Lemma ist notwendig, nicht hinreichend. Die Oberflaeche begrenzt Wort, Exponenten und Zerlegungen fuer endliche Berechnung.",
      "El lema es necesario pero no suficiente. La interfaz limita palabra, exponentes y descomposiciones para calculo finito.",
      "O lema e necessario, mas nao suficiente. A interface limita palavra, expoentes e decomposicoes para calculo finito.",
    ),
    example: l(
      "Per {a^n b^n}, scegli w=a^p b^p. Ogni y entro le prime p posizioni contiene solo a; con i=0 i conteggi non coincidono.",
      "For {a^n b^n}, choose w=a^p b^p. Every y in the first p positions contains only a; with i=0 counts differ.",
      "Pour {a^n b^n}, choisissez w=a^p b^p. Tout y dans les p premieres positions ne contient que a; avec i=0 les comptes different.",
      "Fuer {a^n b^n} waehle w=a^p b^p. Jedes y in den ersten p Positionen enthaelt nur a; bei i=0 unterscheiden sich die Anzahlen.",
      "Para {a^n b^n}, elige w=a^p b^p. Todo y en primeras p posiciones solo tiene a; con i=0 los conteos difieren.",
      "Para {a^n b^n}, escolha w=a^p b^p. Todo y nas primeiras p posicoes contem so a; com i=0 as contagens diferem.",
    ),
  },
  context_free_pumping: {
    definition: l(
      "Organizza l'analisi del pumping lemma per linguaggi context-free; serve a confutare, non a dimostrare da solo, l'essere context-free.",
      "Organizes the context-free pumping lemma analysis; it refutes but cannot alone prove context-freeness.",
      "Organise l'analyse du lemme de pompage context-free; il refute mais ne prouve pas seul qu'un langage est context-free.",
      "Ordnet die Analyse des kontextfreien Pumping-Lemmas; es widerlegt, beweist aber nicht allein Kontextfreiheit.",
      "Organiza analisis del lema de bombeo libre de contexto; refuta pero no prueba por si solo que sea CFL.",
      "Organiza analise do lema de bombeamento livre de contexto; refuta mas nao prova sozinho ser CFL.",
    ),
    notation: l(
      "Se L e context-free, esiste p: ogni w in L con |w|>=p ha w=uvxyz, |vxy|<=p, |vy|>0 e uv^ixy^iz in L per ogni i>=0.",
      "If L is context-free, some p ensures every w in L with |w|>=p has w=uvxyz, |vxy|<=p, |vy|>0, and uv^ixy^iz in L for every i>=0.",
      "Si L est context-free, il existe p: tout w de longueur au moins p a w=uvxyz, |vxy|<=p, |vy|>0 et uv^ixy^iz dans L pour tout i>=0.",
      "Ist L kontextfrei, gibt es p: jedes w mit |w|>=p hat w=uvxyz, |vxy|<=p, |vy|>0 und uv^ixy^iz in L fuer jedes i>=0.",
      "Si L es libre de contexto, existe p: todo w con |w|>=p tiene w=uvxyz, |vxy|<=p, |vy|>0 y uv^ixy^iz en L para todo i>=0.",
      "Se L e livre de contexto, existe p: todo w com |w|>=p tem w=uvxyz, |vxy|<=p, |vy|>0 e uv^ixy^iz em L para todo i>=0.",
    ),
    prerequisites: l(
      "Fornisci una parola candidata lunga almeno p. Devi ragionare su tutte le cinque-partizioni compatibili con la finestra di lunghezza p.",
      "Provide a candidate word at least p long. Reason over every five-part split compatible with the length-p window.",
      "Fournissez un mot candidat long d'au moins p. Raisonnez sur chaque partition en cinq compatible avec la fenetre p.",
      "Gib ein Kandidatenwort mit mindestens p Zeichen. Betrachte jede Fuenfteilung, die zum p-Fenster passt.",
      "Proporciona palabra candidata de al menos p. Razona sobre cada particion en cinco compatible con ventana p.",
      "Forneca palavra candidata com pelo menos p. Raciocine sobre cada particao em cinco compativel com janela p.",
    ),
    procedure: procedure(
      l(
        "Assumi che L sia context-free e considera p arbitrario.",
        "Assume L is context-free and consider arbitrary p.",
        "Supposez L context-free et considerez p arbitraire.",
        "Nimm an, L sei kontextfrei, und betrachte beliebiges p.",
        "Supone L libre de contexto y considera p arbitrario.",
        "Suponha L livre de contexto e considere p arbitrario.",
      ),
      l(
        "Scegli w in L con |w|>=p e classifica ogni uvxyz con |vxy|<=p e |vy|>0.",
        "Choose w in L with |w|>=p and classify every uvxyz with |vxy|<=p and |vy|>0.",
        "Choisissez w dans L avec |w|>=p et classez chaque uvxyz avec |vxy|<=p et |vy|>0.",
        "Waehle w in L mit |w|>=p und klassifiziere jedes uvxyz mit |vxy|<=p und |vy|>0.",
        "Elige w en L con |w|>=p y clasifica cada uvxyz con |vxy|<=p y |vy|>0.",
        "Escolha w em L com |w|>=p e classifique cada uvxyz com |vxy|<=p e |vy|>0.",
      ),
      l(
        "Per ogni caso trova un esponente i che fa uscire uv^ixy^iz da L.",
        "For every case find an exponent i that takes uv^ixy^iz outside L.",
        "Pour chaque cas trouvez un exposant i faisant sortir uv^ixy^iz de L.",
        "Finde fuer jeden Fall ein i, das uv^ixy^iz aus L herausfuehrt.",
        "Para cada caso encuentra un i que saque uv^ixy^iz de L.",
        "Para cada caso encontre um i que retire uv^ixy^iz de L.",
      ),
    ),
    interpretation: l(
      "v e y vengono pompati insieme. Le partizioni enumerate sono casi da chiudere con un argomento sulla struttura della parola.",
      "v and y are pumped together. The listed partitions are cases to close with an argument about word structure.",
      "v et y sont pompes ensemble. Les partitions listees sont des cas a conclure par un argument sur la structure du mot.",
      "v und y werden gemeinsam gepumpt. Die gelisteten Teilungen sind Faelle, die mit einem Strukturargument geschlossen werden.",
      "v e y se bombean juntos. Las particiones listadas son casos a cerrar con argumento sobre estructura de palabra.",
      "v e y sao bombeados juntos. As particoes listadas sao casos a fechar com argumento sobre estrutura da palavra.",
    ),
    limits: l(
      "Il lemma e necessario ma non sufficiente. I limiti dell'interfaccia rendono finita l'enumerazione, non sostituiscono una dimostrazione.",
      "The lemma is necessary but not sufficient. Interface limits make enumeration finite; they do not replace a proof.",
      "Le lemme est necessaire mais non suffisant. Les limites rendent l'enumeration finie sans remplacer une preuve.",
      "Das Lemma ist notwendig, nicht hinreichend. Oberflaechenlimits machen die Aufzaehlung endlich, ersetzen aber keinen Beweis.",
      "El lema es necesario pero no suficiente. Limites de interfaz hacen enumeracion finita, no sustituyen prueba.",
      "O lema e necessario, mas nao suficiente. Limites da interface tornam enumeracao finita, nao substituem prova.",
    ),
    example: l(
      "Per {a^n b^n c^n}, scegli w=a^p b^p c^p. La finestra vxy non puo coprire tutti e tre i blocchi; pompando si rompe almeno un'uguaglianza.",
      "For {a^n b^n c^n}, choose w=a^p b^p c^p. The vxy window cannot cover all three blocks; pumping breaks at least one equality.",
      "Pour {a^n b^n c^n}, prenez w=a^p b^p c^p. La fenetre vxy ne couvre pas les trois blocs; pomper brise une egalite.",
      "Fuer {a^n b^n c^n} waehle w=a^p b^p c^p. Das vxy-Fenster kann nicht alle drei Bloecke abdecken; Pumpen bricht eine Gleichheit.",
      "Para {a^n b^n c^n}, elige w=a^p b^p c^p. Ventana vxy no cubre tres bloques; bombear rompe una igualdad.",
      "Para {a^n b^n c^n}, escolha w=a^p b^p c^p. Janela vxy nao cobre tres blocos; bombear quebra uma igualdade.",
    ),
  },
};
