import type { MachineKind } from "./domain";

export type ModelMeta = {
  kind: MachineKind;
  code: string;
  name: string;
  shortName: string;
  description: string;
  family: string;
  accent: string;
  glyph: "nodes" | "tape" | "stack" | "grammar" | "branch" | "tokens";
  visual: boolean;
};

export const catalogue: ModelMeta[] = [
  {
    kind: "dfa",
    code: "DFA",
    name: "Automa a stati finiti deterministico",
    shortName: "Automa deterministico",
    description: "Un solo percorso possibile per ogni simbolo letto.",
    family: "Automi finiti",
    accent: "violet",
    glyph: "nodes",
    visual: true,
  },
  {
    kind: "nfa",
    code: "NFA",
    name: "Automa a stati finiti non deterministico",
    shortName: "Automa non deterministico",
    description: "Percorsi alternativi e transizioni epsilon.",
    family: "Automi finiti",
    accent: "blue",
    glyph: "branch",
    visual: true,
  },
  {
    kind: "mealy",
    code: "MEALY",
    name: "Trasduttore di Mealy",
    shortName: "Macchina di Mealy",
    description: "Produce un simbolo durante ogni transizione.",
    family: "Trasduttori",
    accent: "cyan",
    glyph: "nodes",
    visual: true,
  },
  {
    kind: "moore",
    code: "MOORE",
    name: "Trasduttore di Moore",
    shortName: "Macchina di Moore",
    description: "Associa un output a ciascuno stato visitato.",
    family: "Trasduttori",
    accent: "cyan",
    glyph: "nodes",
    visual: true,
  },
  {
    kind: "pda",
    code: "PDA",
    name: "Automa a pila",
    shortName: "Automa a pila",
    description: "Modella memoria LIFO insieme allo stato corrente.",
    family: "Automi a memoria",
    accent: "orange",
    glyph: "stack",
    visual: true,
  },
  {
    kind: "turing",
    code: "TM",
    name: "Macchina di Turing",
    shortName: "Macchina di Turing",
    description: "Nastro, testina e funzione di transizione espliciti.",
    family: "Macchine di Turing",
    accent: "rose",
    glyph: "tape",
    visual: true,
  },
  {
    kind: "multiTuring",
    code: "MTM",
    name: "Macchina di Turing multinastro",
    shortName: "Turing multinastro",
    description: "Coordina più nastri e più testine nello stesso passo.",
    family: "Macchine di Turing",
    accent: "rose",
    glyph: "tape",
    visual: true,
  },
  {
    kind: "petri",
    code: "PN",
    name: "Rete di Petri",
    shortName: "Rete di Petri",
    description: "Rappresenta concorrenza, risorse e flusso di token.",
    family: "Reti concorrenti",
    accent: "green",
    glyph: "tokens",
    visual: true,
  },
  {
    kind: "regularGrammar",
    code: "RG",
    name: "Grammatica regolare",
    shortName: "Grammatica regolare",
    description: "Produzioni lineari destre per linguaggi regolari.",
    family: "Grammatiche",
    accent: "yellow",
    glyph: "grammar",
    visual: false,
  },
  {
    kind: "cfg",
    code: "CFG",
    name: "Grammatica context-free",
    shortName: "Grammatica context-free",
    description: "Produzioni, derivazioni e parsing di linguaggi context-free.",
    family: "Grammatiche",
    accent: "yellow",
    glyph: "grammar",
    visual: false,
  },
  {
    kind: "unrestrictedGrammar",
    code: "UG",
    name: "Grammatica non ristretta",
    shortName: "Grammatica non ristretta",
    description: "Riscritture generali con derivazione limitata e ispezionabile.",
    family: "Grammatiche",
    accent: "yellow",
    glyph: "grammar",
    visual: false,
  },
  {
    kind: "regex",
    code: "REGEX",
    name: "Espressione regolare",
    shortName: "Espressione regolare",
    description: "Definisce e simula un linguaggio regolare compatto.",
    family: "Linguaggi regolari",
    accent: "blue",
    glyph: "branch",
    visual: false,
  },
  {
    kind: "lsystem",
    code: "L-SYS",
    name: "Sistema di Lindenmayer",
    shortName: "L-system",
    description: "Applica riscritture parallele per generazioni successive.",
    family: "Sistemi formali",
    accent: "green",
    glyph: "branch",
    visual: false,
  },
  {
    kind: "contextualLsystem",
    code: "C-LSYS",
    name: "L-system contestuale",
    shortName: "L-system contestuale",
    description: "Riscrive simboli in base al loro contesto adiacente.",
    family: "Sistemi formali",
    accent: "green",
    glyph: "branch",
    visual: false,
  },
  {
    kind: "stochasticLsystem",
    code: "S-LSYS",
    name: "L-system stocastico",
    shortName: "L-system stocastico",
    description: "Seleziona produzioni pesate con seme riproducibile.",
    family: "Sistemi formali",
    accent: "green",
    glyph: "branch",
    visual: false,
  },
];

export const metaFor = (kind: MachineKind) => catalogue.find((item) => item.kind === kind) ?? catalogue[0];
